language: python
python:
  - "3.7"
# command to install dependencies
install:
  - conda install -c conda-forge geopandas
#  - pip install -r requirements.txt
  - pip install .
# command to run tests
script:
  "./test/test.py"
