channels:
    - conda-forge
dependencies:
    - python=3.8
    - geopandas=0.8.*
    - rasterstats=0.14.*
    - seaborn=0.11.*
    - spectral=0.22.*
    - pip=20.2.*
    - pip:
        - -r file:requirements/dev_pip.txt