channels:
    - conda-forge
dependencies:
    - python=3.8
    - geopandas=0.9.*
    - rasterstats=0.14.*
    - seaborn=0.11.*
    - spectral=0.22.*
    - tqdm=4.60.*
    - pip=21.*
    - pip:
        - findiff==0.8.*